# Config Datei für die EcoWitt Wetterstation

[influxdb]
url = http://localhost:8086
token = token-from-influxdb
org = org-from-influxdb
bucket = bucket-from-influxdb

[server]
port = 8090
# Hier NONE lassen, um den Key im Debug-Log zu finden
passkey = NONE

[settings]
# Auf True setzen, um Rohdaten und Umrechnungen in der Konsole zu sehen
debug = True